<div class="menu">
    <div class="menu__column">
        <h4><?php echo __('About us')?></h4>
        <ul>
            <li><a href="#"><?php echo __('Show Enviably Me Story')?></a></li>
            <li><a href="#"><?php echo __('Melissa Story')?></a></li>
            <li><a href="#"><?php echo __('Stores')?></a></li>
            <li><a href="#"><?php echo __('Join Enviably Me')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4><?php echo __('Customer care')?></h4>
        <ul>
            <li><a href="#" title="<?php echo __('Orders & Delivery')?>"><?php echo __('Orders & Delivery')?></a></li>
            <li><a href="#" title="<?php echo __('Returns & Exchanges')?>"><?php echo __('Returns & Exchanges')?></a></li>
            <li><a href="#" title="<?php echo __('FAQ')?>"><?php echo __('FAQ')?></a></li>
            <li><a href="#" title="<?php echo __('Contact us')?>"><?php echo __('Contact us')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <img src='<?php echo $this->getViewFileUrl('Magento_Cms::images/paypal.png'); ?>'/>
        <img src='<?php echo $this->getViewFileUrl('Magento_Cms::images/stripe.jpeg'); ?>'/>
    </div>
</div>
<hr>
<div class="bottom-footer-box">
    <div class="bottom-footer-link">Terms & Conditions</div>
    <div class="bottom-footer-link"> Data Policy</div>
    <div class="bottom-footer-link"> Cookies</div>
</div>

