<div class="row" style="float: left; width: 33.33%; padding: 100px;">
    <div class="column">
        <h3>About us</h3>
        <div class="page-links">Show Enviably Me Story</div>
        <div class="page-links">Melissa Story</div>
        <div class="page-links">Stores</div>
        <div class="page-links">Join Enviably Me</div>
    </div>
    <div class="column">
        <h3>Customer care</h3>
        <div class="footer-links">Orders &amp; Delivery</div>
        <div class="footer-links">Returns &amp; Exchanges</div>
        <div class="footer-links">FAQ: now only a link</div>
        <div class="footer-links">Contact us</div>
    </div>
</div>